<?php 
$suffix = (defined('DEBUG_JS') && DEBUG_JS) ? "-debug" : "";  



return array(
	"jquery/jquery.js",
	"jquery/jquery.tools.min.js",
	"jquery/jquery.collapsible.js",
	"extjs/adapter/jquery/ext-jquery-adapter.js",	
	"jquery/color-picker/modcoder_excolor/jquery.modcoder.excolor.js",
	"wztooltip/wz_tooltip.js",
	"extjs/adapter/ext/ext-base.js",
	"extjs/ext-all$suffix.js",
	"og/overrides/extfix.js",
	"og/Helpers.js",
	"og/og.js",
	"og/InfinitePagingToolbar.js",
	"og/HttpProvider.js",
	"og/GooProxy.js",
	"og/QuickAdd.js",
	"og/overrides/TreePanel.js",
	"og/overrides/TreeNode.js",
	"og/MemberChooserTreeLoader.js",	
	"og/Ext.ux.layout.MultiAccordion.js",
	"og/Ext.ux.layout.Horizontal.js",
	"og/ExtendedDialog.js",
	"og/Sound.js",
	"og/LoginDialog.js",
	"og/HtmlPanel.js",
	"og/MemberTree.js",	
	"og/MemberChooserPanel.js",	
	"og/MemberChooserTree.js",	
	"og/MemberChooser.js",	
	"og/ContentPanelLayout.js",
	"og/ContentPanel.js",
	"og/ContextManager.js",
	"og/DateField.js",
	"og/UserGroupPicker.js",
	"og/Permissions.js",
	"og/layout.js",
	"og/modules/dashboardComments.js",
	"og/modules/addMemberForm.js",
	"og/modules/memberSelector.js",
	"og/ofc.js",
	"og/Breadcrumbs.js",
	"og/MemberCombo.js",
	"h5f.min.js",
	"og/main.js",
	"jquery/bootstrap-dropdown.js",
	"jquery/bootstrap-button.js"
);

